### ISSUE TITLE
amazing app! more icons please 🙏

### ISSUE THREAD

**Issue by pchouinardupgrade** [tr1ckyf0x/wakeonlan-ios#27]
this app is amazing!

my only suggestion: please add more icons

for example I have two gaming PC and none of the icons truly match. maybe like a tower case icon on something like that would be perfect

or ability to use a custom image would be even better

**Comment by tr1ckyf0x** [comment]
@pchouinardupgrade We use Apple's built-in SF Symbols as host icons, and avoid using binary images in the app to reduce it's size. Moreover, it would require our designer to draw images, but she is busy now on another project. However, if you can provide us with vector images in the same style, I will add them to the app for you.
