### ISSUE TITLE
iOS 16 bug - probably

### ISSUE THREAD

**Issue by fdiengdoh** [tr1ckyf0x/wakeonlan-ios#38]
I upgraded my iPhone 12 Pro to iOS 16, and the app can't wake my computer anymore. Prior to that it was great.

**Comment by tr1ckyf0x** [comment]
Thank you for the issue. We will take it in work asap.

**Comment by fdiengdoh** [comment]
Additional information that may help.

- I deleted the app, then re-installed. Same problem
- I check in settings earlier there is an option to allow Network access but after I re-install that option disappeared.

**Comment by tr1ckyf0x** [comment]
@fdiengdoh I found that multicast packet are broken in our production build on iOS 16. As a workaround you can specify IP address of the target machine

**Comment by tr1ckyf0x** [comment]
iOS 16 requires allowance from Apple to use multicast packets. It will take some time for their response.

**Comment by fdiengdoh** [comment]
thanks @tr1ckyf0x, IP address of target machine works. hope you could fix this soon.

**Comment by fdiengdoh** [comment]
Thanks for the fix, the workaround of using ip sometimes fail to wake my pc. But this ensure it always wake.
