### ISSUE TITLE
support hostName？Not only wake by local IP.

### ISSUE THREAD

**Issue by CraKeyBoy** [tr1ckyf0x/wakeonlan-ios#41]

**Comment by CraKeyBoy** [comment]
can we use hostName to wake my device? Not only by local IP.

**Comment by tr1ckyf0x** [comment]
It needs research, but thank you for the proposal

**Comment by CraKeyBoy** [comment]
ok，thx. 😆

**Comment by tr1ckyf0x** [comment]
966976d39f239ec1dd166329b2cca39b5d3bbbd6
