### ISSUE TITLE
 Allow users to enter the DDNS address in the IP address bar

### ISSUE THREAD

**Issue by KlausXXX95** [tr1ckyf0x/wakeonlan-ios#47]
Firstly, I do looooove this amazing tiny but beautiful app! This is the best WOL app in the appstore! Thank you for providing us this. 
I'd like to make a small suggestion. I hope the app can allow me to input my DDNS Domain Name in the IP Address bar, so that I can realize the Wake-on-wan function.
Agagin, thank you for your creativity and effort
Best wishes

**Comment by tr1ckyf0x** [comment]
Duplicate. #41

Thank you for the feedback. This feature requires some refactoring, so it will not be released soon, but we consider to implement it maybe within a month or two.

**Comment by KlausXXX95** [comment]
Thanks for your effort！

**Comment by kamto7** [comment]
waiting for

**Comment by tr1ckyf0x** [comment]
966976d39f239ec1dd166329b2cca39b5d3bbbd6
