### ISSUE TITLE
Siri shortcut not working

### ISSUE THREAD

**Issue by IAmNotAJerk** [tr1ckyf0x/wakeonlan-ios#49]
It shows “there was a problem communicating with the app” whenever the wake host command is triggered through manual prompt or other automation triggers. 

Packet and be sent no problem using the app. 

Please let me know if you need extra info and how to send them to you.

**Comment by tr1ckyf0x** [comment]
Fixed. 71c6dd211da6b9911c7dde7254f70929a31a6eaa
