### ISSUE TITLE
Add Siri command

### ISSUE THREAD

**Issue by HugoFerCanz** [tr1ckyf0x/wakeonlan-ios#53]

**Comment by tr1ckyf0x** [comment]
Hello.
Could you, please, provide more details? We already have Siri integration

**Comment by HugoFerCanz** [comment]
How works the Siri integration?

**Comment by tr1ckyf0x** [comment]
1. Open app "Shortcuts"
2. Find "Awake"
3. Choose "Wake host" action

**Comment by tr1ckyf0x** [comment]
When you shortcut is created you can ask Siri to launch it

**Comment by HugoFerCanz** [comment]
Done! Thank you

**Comment by tr1ckyf0x** [comment]
You are welcome
