### ISSUE TITLE
Allow users to use without connecting to WiFi

### ISSUE THREAD

**Issue by Whichbfj28** [tr1ckyf0x/wakeonlan-ios#55]
1、Allow users to use without connecting to WiFi
2、Cooperate with DDNS #47 . We can remotely wake up our home computers through the mobile network

**Comment by tr1ckyf0x** [comment]
WIP
Expect this and following features soon:
#50
#47
#41

Unfortunately, neither me nor @Dm94st have enough time to implement all these requests ASAP, as we both have full-time jobs, however, these features will be implemented within several months.

**Comment by tr1ckyf0x** [comment]
I have problems with CoreData CloudKit migrations, so these issues won't be resolved soon. Maybe I will return to these issues later.

**Comment by tr1ckyf0x** [comment]
e57f11bcfe86e05bd37b1d29b43f81795a9103db
